{\rtf1\ansi\ansicpg1252\cocoartf2580
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fnil\fcharset0 Monaco;}
{\colortbl;\red255\green255\blue255;\red89\green142\blue166;\red36\green36\blue36;\red197\green197\blue197;
\red239\green239\blue239;\red126\green155\blue71;\red240\green178\blue98;}
{\*\expandedcolortbl;;\cssrgb\c41569\c62353\c70980;\cssrgb\c18824\c18824\c18824;\cssrgb\c81569\c81569\c81569;
\cssrgb\c94902\c94902\c94902;\cssrgb\c56471\c66275\c34902;\cssrgb\c95686\c74902\c45882;}
\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\deftab720
\pard\pardeftab720\partightenfactor0

\f0\fs28 \cf2 \cb3 \expnd0\expndtw0\kerning0
\shad\shadx0\shady-20\shadr0\shado1 \shadc0 plugins\cf4 :\cf5 \
  \cf4 -\cf5  \cf6 jekyll-relative-links\cf5 \
\cf2 relative_links\cf4 :\cf5 \
  \cf2 enabled\cf4 :\cf5  \cf7 true\cf5 \
  \cf2 collections\cf4 :\cf5  \cf7 true\cf5 \
\cf2 include\cf4 :\cf5 \
  \cf4 -\cf5  \cf6 CONTRIBUTING.md\cf5 \
  \cf4 -\cf5  \cf6 README.md\cf5 \
  \cf4 -\cf5  \cf6 LICENSE.md\cf5 \
  \cf4 -\cf5  \cf6 COPYING.md\cf5 \
  \cf4 -\cf5  \cf6 CODE_OF_CONDUCT.md\cf5 \
  \cf4 -\cf5  \cf6 CONTRIBUTING.md\cf5 \
  \cf4 -\cf5  \cf6 ISSUE_TEMPLATE.md\cf5 \
  \cf4 -\cf5  \cf6 PULL_REQUEST_TEMPLATE.md}